


name: CI
env:
  AZURE_WEBAPP_NAME: openhackad69qxk8userjava
  CONTAINER_REGISTRY: openhackad69qxk8acr.azurecr.io
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ java-branch ]
    paths: 
      - apis/user-java/**
      - .github/workflows/java-cd.yml
    
  pull_request:
    branches: [ java-branch ]
    paths: 
      - apis/user-java/**
      - .github/workflows/java-cd.yml

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy-to-dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: java-branch
             # Runs a single command using the runners shell

      - name: Run a one-line script
        working-directory: apis/user-java
        run: mvn verify
      
      # Create an issue on failure
      - name: Indentify failure and create issue 
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
        with:
          filename : .github/ISSUE_TEMPLATE_custom.md
          
      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: ACR authentication
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}    
      - name: Docker Build & Push to ACR
        run: |
          docker build . -t ${{ env.CONTAINER_REGISTRY }}/devopsoh/user-java:${{ github.sha }}
          docker push ${{ env.CONTAINER_REGISTRY }}/devopsoh/user-java:${{ github.sha }} 
          
      - name: 'Deploy to Azure Web App for Container'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} 
          images: ${{ env.CONTAINER_REGISTRY }}/devopsoh/user-java:${{ github.sha }}

